// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySinhVien.Model;

#nullable disable

namespace QuanLySinhVien.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250621041547_dothihuyen")]
    partial class dothihuyen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySinhVien.Model.SinhVien", b =>
                {
                    b.Property<int>("masv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("masv"));

                    b.Property<string>("gioitinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("tensv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("masv");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            masv = 1,
                            gioitinh = "Nữ",
                            lop = "Tina4",
                            ngaysinh = new DateTime(2004, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            tensv = "Huyền"
                        },
                        new
                        {
                            masv = 2,
                            gioitinh = "Nam",
                            lop = "Tina22",
                            ngaysinh = new DateTime(2004, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            tensv = "Trọng"
                        },
                        new
                        {
                            masv = 3,
                            gioitinh = "Nữ",
                            lop = "QTMa3",
                            ngaysinh = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            tensv = "Hoa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
