// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebSinhVien.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20250621053101_kqdothihuyen")]
    partial class kqdothihuyen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebSinhVien.Models.KetQua", b =>
                {
                    b.Property<int>("makq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("makq"));

                    b.Property<int?>("SinhVienmasv")
                        .HasColumnType("int");

                    b.Property<float>("diem")
                        .HasColumnType("real");

                    b.Property<int>("masv")
                        .HasColumnType("int");

                    b.Property<string>("monhoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("makq");

                    b.HasIndex("SinhVienmasv");

                    b.ToTable("KetQua");

                    b.HasData(
                        new
                        {
                            makq = 1,
                            diem = 8.5f,
                            masv = 1,
                            monhoc = "Toán"
                        },
                        new
                        {
                            makq = 2,
                            diem = 7f,
                            masv = 2,
                            monhoc = "Văn"
                        },
                        new
                        {
                            makq = 3,
                            diem = 6.8f,
                            masv = 1,
                            monhoc = "Lý"
                        },
                        new
                        {
                            makq = 4,
                            diem = 9f,
                            masv = 3,
                            monhoc = "Hóa"
                        },
                        new
                        {
                            makq = 5,
                            diem = 7.5f,
                            masv = 2,
                            monhoc = "Anh"
                        });
                });

            modelBuilder.Entity("WebSinhVien.Models.SinhVien", b =>
                {
                    b.Property<int>("masv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("masv"));

                    b.Property<string>("gioitinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("tensv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("masv");

                    b.ToTable("SinhVien");

                    b.HasData(
                        new
                        {
                            masv = 1,
                            gioitinh = "Nữ",
                            lop = "Tina4",
                            ngaysinh = new DateTime(2004, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            tensv = "Huyền"
                        },
                        new
                        {
                            masv = 2,
                            gioitinh = "Nam",
                            lop = "Tina22",
                            ngaysinh = new DateTime(2004, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            tensv = "Trọng"
                        },
                        new
                        {
                            masv = 3,
                            gioitinh = "Nữ",
                            lop = "QTMa3",
                            ngaysinh = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            tensv = "Hoa"
                        });
                });

            modelBuilder.Entity("WebSinhVien.Models.KetQua", b =>
                {
                    b.HasOne("WebSinhVien.Models.SinhVien", "SinhVien")
                        .WithMany("KetQuas")
                        .HasForeignKey("SinhVienmasv");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("WebSinhVien.Models.SinhVien", b =>
                {
                    b.Navigation("KetQuas");
                });
#pragma warning restore 612, 618
        }
    }
}
